### ISSUE TITLE
contact?

### ISSUE THREAD

**Issue by fares57** [Sandbird/covid19-Greece#2]
Καλησπέρα, είμαι ο Γιάννης που μιλούσαμε στο εξελ του nyrros! 

Εχεις κάποιο μέηλ που μπορούμε να σε βρούμε; Ευχαριστώ πολύ.

Με εκτίμηση, 
[Γιάννης Κουτίβας](https://www.linkedin.com/in/giannis-koutivas/)

**Comment by Sandbird** [comment]
> Εχεις κάποιο μέηλ που μπορούμε να σε βρούμε; Ευχαριστώ πολύ.

Χίλια συγνώμη Γιάννη, δεν έλαβα κάποια ειδοποίηση για το ticket που ανοίχτηκε. Τώρα το είδα το μήνυμα. 
Στείλε μου στο sandbird2 στο γνωστό gmail.com
